apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cjpod-controller
  namespace: cjpod-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cjpod-controller
